spring:
  output:
    ansi:
      enabled: detect

  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    content-type: text/html
    cache: false

  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
        enabled: true
        max-file-size: 512MB
        max-request-size: 512MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_edu?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: admin
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  path: /log
  level:
    com:
      outstudio:
        weixin: debug
  file: log.log


fileSavedPath: file:/home/ubuntu/weixin/

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080



